// examples/react-test-app-ts/src/App.tsx
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import { Client } from 'contensis-delivery-api';

class App extends Component {

  constructor(props) {
    super(props);
    this.state = {
      error: null,
      isLoaded: false,
      project: null
    };
  }

  componentDidMount() {

    let client = Client.create({
      accessToken: 'xxxxx',
      projectId: 'website',
      rootUrl: 'https://cms-example.cloud.contensis.com'
    });
    client.project.get().then(project => {
      this.setState({
        isLoaded: true,
        project: project
      });
    },
      error => {
        this.setState({
          isLoaded: true,
          error
        });
      });
  }

  render() {
    const { error, isLoaded, project } = this.state as any;
    if (error) {
      return <div>Error: {error.message}</div>;
    } else if (!isLoaded) {
      return <div>Loading...</div>;
    } else {
      return (
        <div className="App">
          <header className="App-header">
            <img src={logo} className="App-logo" alt="logo" />
            <p>
              Connected to Contensis project {project.name}
            </p>
            <a
              className="App-link"
              href="https://reactjs.org"
              target="_blank"
              rel="noopener noreferrer"
            >
              Learn React
            </a>
          </header>
        </div>
      );
    }
  }

}

export default App;

// examples/angular-test-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { Client } from 'contensis-delivery-api';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  title = 'angular-test-app';
  contensisProjectName = '';
  error = null;

  ngOnInit(): void {
    const client = Client.create({
      accessToken: 'xxxxx',
      projectId: 'website',
      rootUrl: 'https://cms-example.cloud.contensis.com'
    });
    client.project.get().then(project => {
      this.contensisProjectName = project.name;
    },
      error => {
        this.error = error;
      }
    );
  }

}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>
<h2 *ngIf="!contensisProjectName">Connecting to Contensis project ...</h2>
<h2 *ngIf="!!contensisProjectName">Connected to Contensis project: {{contensisProjectName}}</h2>
<p *ngIf="!!error">Error: {{error}}</p>
